"""
TradeBack Economics & Customer Lifecycle Model: Assumptions Registry.

Single source of truth for all baseline parameters, operational levers,
and taxonomy classifications.

Taxonomy Tiers:
- [Observed]: Empirical company/warehouse data (e.g., labor/QC costs).
- [External Benchmark]: Credible Indian e-commerce / D2C benchmarks (Meesho, Urbanic, Nykaa).
- [Management Assumption]: Founding team commercial policy choice.
- [Model Assumption]: Structural modeling choice or proxy.
- [Unknown]: High uncertainty parameter to be experimentally validated in pilot.
"""

from dataclasses import dataclass, field
from typing import Dict, Any, List

@dataclass
class ParameterMeta:
    name: str
    display_name: str
    default_value: float
    min_value: float
    max_value: float
    unit: str
    taxonomy_tier: str
    source_description: str
    adr_reference: str = ""

# Complete Parameter Registry with Metadata (20-Variable Master Registry)
PARAMETER_REGISTRY: Dict[str, ParameterMeta] = {
    # Group 1: Baseline Customer Economics
    "aov": ParameterMeta(
        name="aov",
        display_name="Average Order Value (AOV)",
        default_value=1300.0,
        min_value=1000.0,
        max_value=1700.0,
        unit="₹",
        taxonomy_tier="[External Benchmark]",
        source_description="Mid-market Indian apparel standard (Urbanic, Snitch, Westside online).",
    ),
    "gross_margin_pct": ParameterMeta(
        name="gross_margin_pct",
        display_name="Product Gross Margin (GM_prod)",
        default_value=0.50,
        min_value=0.42,
        max_value=0.58,
        unit="%",
        taxonomy_tier="[External Benchmark]",
        source_description="Fabric + garment manufacturing COGS (Surat/Tirupur manufacturing hub).",
    ),
    "forward_fulfillment_cost": ParameterMeta(
        name="forward_fulfillment_cost",
        display_name="Forward Fulfillment Freight (C_fulfill)",
        default_value=70.0,
        min_value=55.0,
        max_value=90.0,
        unit="₹/order",
        taxonomy_tier="[External Benchmark]",
        source_description="Forward courier delivery (Shiprocket/Delhivery) + warehouse pack cost.",
    ),
    "cac": ParameterMeta(
        name="cac",
        display_name="Initial CAC (CAC_init)",
        default_value=400.0,
        min_value=280.0,
        max_value=550.0,
        unit="₹",
        taxonomy_tier="[External Benchmark]",
        source_description="Blended Meta & Google first-purchase acquisition cost in India.",
    ),
    "baseline_annual_orders": ParameterMeta(
        name="baseline_annual_orders",
        display_name="Baseline Frequency (f_base)",
        default_value=2.50,
        min_value=1.80,
        max_value=3.20,
        unit="orders/year",
        taxonomy_tier="[External Benchmark]",
        source_description="Annual repeat purchasing frequency across Indian D2C apparel.",
    ),
    "customer_lifespan_months": ParameterMeta(
        name="customer_lifespan_months",
        display_name="Customer Lifespan (T_active)",
        default_value=18.0,
        min_value=12.0,
        max_value=24.0,
        unit="months",
        taxonomy_tier="[Model Assumption]",
        source_description="Months customer remains active before non-contractual churn.",
    ),
    "repeat_ad_cac": ParameterMeta(
        name="repeat_ad_cac",
        display_name="Repeat Ad CAC (CAC_rep)",
        default_value=150.0,
        min_value=90.0,
        max_value=220.0,
        unit="₹/order",
        taxonomy_tier="[External Benchmark]",
        source_description="Cost per paid reacquired order via Meta retargeting & Google DPA.",
    ),
    "paid_repeat_share": ParameterMeta(
        name="paid_repeat_share",
        display_name="Paid Repeat Share (p_paid rep)",
        default_value=0.50,
        min_value=0.30,
        max_value=0.70,
        unit="%",
        taxonomy_tier="[Model Assumption]",
        source_description="% of repeat orders requiring paid ad reacquisition (vs organic/CRM flows).",
    ),

    # Group 2: TradeBack Policy & Customer Levers
    "tradeback_adoption_rate": ParameterMeta(
        name="tradeback_adoption_rate",
        display_name="Customer Adoption Rate (α)",
        default_value=0.40,
        min_value=0.15,
        max_value=0.65,
        unit="%",
        taxonomy_tier="[Unknown]",
        source_description="% of acquired customers who enroll in TradeBack. Must validate in pilot.",
        adr_reference="ADR-004",
    ),
    "order_utilization_rate": ParameterMeta(
        name="order_utilization_rate",
        display_name="Order Utilization Rate (u)",
        default_value=0.75,
        min_value=0.50,
        max_value=0.90,
        unit="%",
        taxonomy_tier="[Unknown]",
        source_description="% of eligible orders where customer actually returns a garment.",
        adr_reference="ADR-002",
    ),
    "causal_frequency_uplift": ParameterMeta(
        name="causal_frequency_uplift",
        display_name="Causal Frequency Uplift (Δf)",
        default_value=0.50,
        min_value=0.00,
        max_value=1.20,
        unit="orders/year",
        taxonomy_tier="[Unknown]",
        source_description="Truly incremental orders/year caused strictly by TradeBack credit incentive.",
        adr_reference="ADR-002",
    ),
    "tradeback_credit_pct": ParameterMeta(
        name="tradeback_credit_pct",
        display_name="TradeBack Credit % (Credit_%)",
        default_value=0.20,
        min_value=0.10,
        max_value=0.30,
        unit="%",
        taxonomy_tier="[Management Assumption]",
        source_description="Instant cart discount percentage applied at replacement checkout.",
        adr_reference="ADR-001",
    ),
    "credit_breakage_pct": ParameterMeta(
        name="credit_breakage_pct",
        display_name="Credit Breakage % (β)",
        default_value=0.0,
        min_value=0.0,
        max_value=0.0,
        unit="%",
        taxonomy_tier="[Model Assumption]",
        source_description="Locked at 0.0% because credit is applied instantly at replacement cart.",
        adr_reference="ADR-001",
    ),
    "ad_savings_pct": ParameterMeta(
        name="ad_savings_pct",
        display_name="Avoided Ad Factor (S_ad)",
        default_value=0.60,
        min_value=0.30,
        max_value=0.85,
        unit="%",
        taxonomy_tier="[Management Assumption]",
        source_description="Ad efficiency gain on TradeBack returns replacing paid retargeting.",
    ),
    "stranded_garments_terminal": ParameterMeta(
        name="stranded_garments_terminal",
        display_name="Terminal Stranded Garments (N_stranded)",
        default_value=1.0,
        min_value=1.0,
        max_value=2.0,
        unit="garments",
        taxonomy_tier="[Model Assumption]",
        source_description="Final garments purchased before churn permanently stranded in closets.",
        adr_reference="ADR-002",
    ),

    # Group 3: Reverse Logistics & Inspection Friction
    "doorstep_swap_cost": ParameterMeta(
        name="doorstep_swap_cost",
        display_name="Doorstep Swap Fee (C_swap)",
        default_value=35.0,
        min_value=25.0,
        max_value=50.0,
        unit="₹/return",
        taxonomy_tier="[External Benchmark]",
        source_description="3PL contractual carrier fee for courier reverse pickup during forward delivery.",
        adr_reference="ADR-003",
    ),
    "swap_failure_rate": ParameterMeta(
        name="swap_failure_rate",
        display_name="Swap Failure Rate (P_fail)",
        default_value=0.15,
        min_value=0.08,
        max_value=0.25,
        unit="%",
        taxonomy_tier="[External Benchmark]",
        source_description="Frequency of doorstep handover failure (customer unavailable/unready).",
        adr_reference="ADR-003",
    ),
    "standalone_reverse_cost": ParameterMeta(
        name="standalone_reverse_cost",
        display_name="Standalone Reverse Fee (C_rev)",
        default_value=65.0,
        min_value=50.0,
        max_value=85.0,
        unit="₹/return",
        taxonomy_tier="[External Benchmark]",
        source_description="Fallback dedicated pickup cost when doorstep swap fails.",
        adr_reference="ADR-003",
    ),
    "swap_fail_rto_rate": ParameterMeta(
        name="swap_fail_rto_rate",
        display_name="Swap-Induced RTO Rate (P_RTO)",
        default_value=0.10,
        min_value=0.05,
        max_value=0.20,
        unit="%",
        taxonomy_tier="[Model Assumption]",
        source_description="% of failed swaps causing forward parcel rejection and RTO.",
        adr_reference="ADR-003",
    ),
    "rto_freight_burn": ParameterMeta(
        name="rto_freight_burn",
        display_name="RTO Freight Penalty",
        default_value=130.0,
        min_value=100.0,
        max_value=180.0,
        unit="₹/RTO",
        taxonomy_tier="[External Benchmark]",
        source_description="Forward freight (₹70) + return freight (₹60) wasted on RTO orders.",
        adr_reference="ADR-003",
    ),
    "qc_inspection_cost": ParameterMeta(
        name="qc_inspection_cost",
        display_name="Intake QC & Steam Cost (C_QC)",
        default_value=45.0,
        min_value=30.0,
        max_value=70.0,
        unit="₹/garment",
        taxonomy_tier="[Observed]",
        source_description="In-house warehouse labor to unbox, inspect, steam-sanitize, and barcode.",
    ),

    # Group 4: Secondary Salvage Routes & Costs
    "gross_realized_salvage": ParameterMeta(
        name="gross_realized_salvage",
        display_name="Gross Realized Salvage E[V_salv]",
        default_value=158.68,
        min_value=90.0,
        max_value=240.0,
        unit="₹/garment",
        taxonomy_tier="[Model Assumption]",
        source_description="5-route probability-weighted clearance cash before collection & QC.",
    ),
    "b2b_route_prob": ParameterMeta(
        name="b2b_route_prob",
        display_name="Route 1: B2B Jobber Probability",
        default_value=0.60,
        min_value=0.30,
        max_value=0.80,
        unit="%",
        taxonomy_tier="[External Benchmark]",
        source_description="Share of garments sold in bulk lots to offline discount jobbers.",
        adr_reference="ADR-006",
    ),
    "b2b_gross_price": ParameterMeta(
        name="b2b_gross_price",
        display_name="B2B Jobber Gross Price",
        default_value=150.0,
        min_value=80.0,
        max_value=250.0,
        unit="₹/garment",
        taxonomy_tier="[External Benchmark]",
        source_description="Gross cash salvage per garment from offline liquidation lots.",
        adr_reference="ADR-006",
    ),
    "b2b_route_cost": ParameterMeta(
        name="b2b_route_cost",
        display_name="B2B Route Cost",
        default_value=10.0,
        min_value=5.0,
        max_value=25.0,
        unit="₹/garment",
        taxonomy_tier="[External Benchmark]",
        source_description="Lot aggregation and B2B freight handling cost per garment.",
    ),
    "d2c_route_prob": ParameterMeta(
        name="d2c_route_prob",
        display_name="Route 2: D2C Resale Probability",
        default_value=0.20,
        min_value=0.0,
        max_value=0.40,
        unit="%",
        taxonomy_tier="[Management Assumption]",
        source_description="Share of Grade A garments resold on refurbished portal.",
    ),
    "d2c_gross_price": ParameterMeta(
        name="d2c_gross_price",
        display_name="D2C Resale Gross Price",
        default_value=450.0,
        min_value=250.0,
        max_value=700.0,
        unit="₹/garment",
        taxonomy_tier="[External Benchmark]",
        source_description="Selling price on refurbished clearance portal.",
    ),
    "d2c_route_cost": ParameterMeta(
        name="d2c_route_cost",
        display_name="D2C Route Cost (Clean/Shoot)",
        default_value=80.0,
        min_value=40.0,
        max_value=120.0,
        unit="₹/garment",
        taxonomy_tier="[External Benchmark]",
        source_description="Specialty photography, dry-cleaning, and re-listing cost.",
    ),
    "d2c_cannibalization_rate": ParameterMeta(
        name="d2c_cannibalization_rate",
        display_name="D2C Cannibalization Rate (θ_cannibal)",
        default_value=0.20,
        min_value=0.0,
        max_value=0.40,
        unit="%",
        taxonomy_tier="[Model Assumption]",
        source_description="Fraction of clearance buyers who would have bought a full-price new item.",
    ),
    "upcycle_route_prob": ParameterMeta(
        name="upcycle_route_prob",
        display_name="Route 3: Upcycling Probability",
        default_value=0.10,
        min_value=0.0,
        max_value=0.20,
        unit="%",
        taxonomy_tier="[Management Assumption]",
        source_description="Share of garments redesigned or remanufactured.",
    ),
    "upcycle_gross_price": ParameterMeta(
        name="upcycle_gross_price",
        display_name="Upcycling Gross Value",
        default_value=160.0,
        min_value=100.0,
        max_value=250.0,
        unit="₹/garment",
        taxonomy_tier="[Management Assumption]",
        source_description="Gross recovered value per upcycled item.",
    ),
    "upcycle_route_cost": ParameterMeta(
        name="upcycle_route_cost",
        display_name="Upcycling Rework Cost",
        default_value=30.0,
        min_value=15.0,
        max_value=50.0,
        unit="₹/garment",
        taxonomy_tier="[Management Assumption]",
        source_description="Tailoring / pattern rework cost per upcycled item.",
    ),
    "recycle_route_prob": ParameterMeta(
        name="recycle_route_prob",
        display_name="Route 4: Industrial Scrap Probability",
        default_value=0.05,
        min_value=0.0,
        max_value=0.15,
        unit="%",
        taxonomy_tier="[External Benchmark]",
        source_description="Share of garments sent to shredding / industrial rag recyclers.",
    ),
    "recycle_gross_price": ParameterMeta(
        name="recycle_gross_price",
        display_name="Industrial Scrap Gross Price",
        default_value=35.0,
        min_value=15.0,
        max_value=60.0,
        unit="₹/garment",
        taxonomy_tier="[External Benchmark]",
        source_description="Scrap price per kg from industrial textile shredders.",
    ),
    "recycle_route_cost": ParameterMeta(
        name="recycle_route_cost",
        display_name="Industrial Scrap Route Cost",
        default_value=5.0,
        min_value=2.0,
        max_value=15.0,
        unit="₹/garment",
        taxonomy_tier="[External Benchmark]",
        source_description="Baling and scrap hauling cost.",
    ),
    "writeoff_route_prob": ParameterMeta(
        name="writeoff_route_prob",
        display_name="Route 5: Loss / Write-off Probability",
        default_value=0.05,
        min_value=0.0,
        max_value=0.15,
        unit="%",
        taxonomy_tier="[Model Assumption]",
        source_description="Severely damaged or stained garments with zero recovery value.",
    ),
    "writeoff_route_cost": ParameterMeta(
        name="writeoff_route_cost",
        display_name="Loss / Write-off Disposal Cost",
        default_value=10.0,
        min_value=5.0,
        max_value=20.0,
        unit="₹/garment",
        taxonomy_tier="[Model Assumption]",
        source_description="Disposal and non-salvageable waste handling fee.",
    ),

    # Group 5: Inventory Delay & Depreciation
    "inventory_holding_days": ParameterMeta(
        name="inventory_holding_days",
        display_name="Inventory Holding Days (t_hold)",
        default_value=45.0,
        min_value=15.0,
        max_value=90.0,
        unit="days",
        taxonomy_tier="[Model Assumption]",
        source_description="Delay from customer pickup to secondary market liquidation.",
    ),
    "monthly_trend_depreciation": ParameterMeta(
        name="monthly_trend_depreciation",
        display_name="Monthly Trend Depreciation Rate",
        default_value=0.05,
        min_value=0.02,
        max_value=0.10,
        unit="%/month",
        taxonomy_tier="[Model Assumption]",
        source_description="Fashion obsolescence discount per 30 days of storage.",
    ),
    "effective_gst_leakage": ParameterMeta(
        name="effective_gst_leakage",
        display_name="Effective GST Leakage %",
        default_value=0.08,
        min_value=0.05,
        max_value=0.12,
        unit="%",
        taxonomy_tier="[External Benchmark]",
        source_description="Net un-recovered tax friction under Indian GST Margin Scheme.",
    ),

    # Group 6: Benchmark System C (Promo Coupon Alternative)
    "benchmark_coupon_discount": ParameterMeta(
        name="benchmark_coupon_discount",
        display_name="System C: Coupon Discount Value",
        default_value=200.0,
        min_value=100.0,
        max_value=300.0,
        unit="₹/order",
        taxonomy_tier="[Management Assumption]",
        source_description="Instant discount voucher given on repeat purchase in System C.",
        adr_reference="ADR-005",
    ),
}

def get_default_assumptions() -> Dict[str, float]:
    """Returns a clean key-value dictionary of all default parameters."""
    return {k: meta.default_value for k, meta in PARAMETER_REGISTRY.items()}
